In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

add = arr + 2
print("Array after adding 2:", add)

multiply = arr * 3
print("Array after multiplying:", multiply)

divide = arr / 2
print("Array after dividing:", divide)


Array after adding 2: [12 22 32 42 52]
Array after multiplying: [ 30  60  90 120 150]
Array after dividing: [ 5. 10. 15. 20. 25.]


In [4]:
import numpy as np
array = np.array([1,2,3,6,4,5])
print("Initial Array:",str(array))
reverse = array[::-1]
print("Reversed array:",str(reverse))
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original Array:")
print(x)
print("Most frequent value in above array:",np.bincount(x).argmax())
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,3]) 
print("Original Array:")
print(y)
print("Most frequent value in above array:",np.bincount(y).argmax())

Initial Array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]
Original Array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in above array: 1
Original Array:
[1 1 1 2 3 4 2 4 3 3 3]
Most frequent value in above array: 3


In [6]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at given index :",arr[0,1])
print("Element at given index:", arr[2,0])

Element at given index : 20
Element at given index: 70


In [14]:
import numpy as np  
arr = np.linspace(10, 100, 25, endpoint = False)  
print("The array over the given range is ",arr)  
print("Dimensions:",arr.ndim)
print("Shape:",arr.shape)
print("Total Elements:",arr.size)
print("Data Type:",arr.dtype)
print("Total Bytes:",arr.nbytes)
b = arr.reshape(25,1)
b
transpose = arr.T
transpose


The array over the given range is  [10.  13.6 17.2 20.8 24.4 28.  31.6 35.2 38.8 42.4 46.  49.6 53.2 56.8
 60.4 64.  67.6 71.2 74.8 78.4 82.  85.6 89.2 92.8 96.4]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200


array([10. , 13.6, 17.2, 20.8, 24.4, 28. , 31.6, 35.2, 38.8, 42.4, 46. ,
       49.6, 53.2, 56.8, 60.4, 64. , 67.6, 71.2, 74.8, 78.4, 82. , 85.6,
       89.2, 92.8, 96.4])

In [16]:
import numpy as np
arr = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean_value = np.mean(arr)
median_value = np.median(arr)
max_value = np.max(arr)
min_value = np.min(arr)
unique_elements = np.unique(arr)

print("Mean:",mean_value)
print("Median:",median_value)
print("Max:",max_value)
print("Min:",min_value)
print("Unique elements:",unique_elements)

print("Reshaped array:", arr.reshape(4,3))

brr = arr.resize(2,3)
print("Resized array :",brr)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array : None
